# Site
name: "HotDeals"
title: "Awesome HotDeals"
description: ""
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /deals
google_analytics: ''
disqus: ''
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: sosohappy0106@gmail.com

# Authors
authors:
  seoys:
    name: seoys
    display_name: seoys
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: sosohappy0106@gmail.com
    web: https://seoys.github.io/deals/
    description: ""
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-9975083238740545"
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
